version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tconnect
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tconnectdb
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"
